### ISSUE TITLE
Calculate subtractor and comparator feedback resistances

### ISSUE THREAD

**Issue by TobiNakamura** [SFUSatClub/Amp_Dev#4]

**Comment by Alenux55** [comment]
Matches the topology in the [datasheet](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjBndDF46jVAhWji1QKHciuBJEQFggoMAA&url=http%3A%2F%2Fwww.qorvo.com%2Fproducts%2Fd%2Fda000557&usg=AFQjCNHC_ltR0_H3U8nbR8DyijuvHESJIQ)
